/*
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CSVsStandaloneSetup extends CSVsStandaloneSetupGenerated {

	public static void doSetup() {
		new CSVsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
