/**
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.csvs;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.agicquel.csvs.csvs.AddExpr#getLeft <em>Left</em>}</li>
 *   <li>{@link com.agicquel.csvs.csvs.AddExpr#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see com.agicquel.csvs.csvs.CsvsPackage#getAddExpr()
 * @model
 * @generated
 */
public interface AddExpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(EqualityExpr)
   * @see com.agicquel.csvs.csvs.CsvsPackage#getAddExpr_Left()
   * @model containment="true"
   * @generated
   */
  EqualityExpr getLeft();

  /**
   * Sets the value of the '{@link com.agicquel.csvs.csvs.AddExpr#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(EqualityExpr value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link com.agicquel.csvs.csvs.EqualityExpr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see com.agicquel.csvs.csvs.CsvsPackage#getAddExpr_Right()
   * @model containment="true"
   * @generated
   */
  EList<EqualityExpr> getRight();

} // AddExpr
