/**
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.csvs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.agicquel.csvs.csvs.CsvsPackage#getAtomicExpr()
 * @model
 * @generated
 */
public interface AtomicExpr extends CsvsExpr
{
} // AtomicExpr
