/**
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.csvs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.agicquel.csvs.csvs.CsvsPackage#getCsvsExpr()
 * @model
 * @generated
 */
public interface CsvsExpr extends PrimaryExpr
{
} // CsvsExpr
