/**
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.csvs;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.agicquel.csvs.csvs.CsvsFactory
 * @model kind="package"
 * @generated
 */
public interface CsvsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "csvs";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.agicquel.com/csvs/CSVs";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "csvs";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CsvsPackage eINSTANCE = com.agicquel.csvs.csvs.impl.CsvsPackageImpl.init();

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.BlockImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 2;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.ProgramImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__COMMANDS = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.CommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.ControlCommandImpl <em>Control Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.ControlCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getControlCommand()
   * @generated
   */
  int CONTROL_COMMAND = 3;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_COMMAND__COND = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Control Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.WhileCommandImpl <em>While Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.WhileCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getWhileCommand()
   * @generated
   */
  int WHILE_COMMAND = 4;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_COMMAND__COND = CONTROL_COMMAND__COND;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_COMMAND__BODY = CONTROL_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>While Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_COMMAND_FEATURE_COUNT = CONTROL_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.IfCommandImpl <em>If Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.IfCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getIfCommand()
   * @generated
   */
  int IF_COMMAND = 5;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_COMMAND__COND = CONTROL_COMMAND__COND;

  /**
   * The feature id for the '<em><b>Then Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_COMMAND__THEN_BODY = CONTROL_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Else Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_COMMAND__ELSE_BODY = CONTROL_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>If Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_COMMAND_FEATURE_COUNT = CONTROL_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.CsvCommandImpl <em>Csv Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.CsvCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCsvCommand()
   * @generated
   */
  int CSV_COMMAND = 6;

  /**
   * The number of structural features of the '<em>Csv Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.LoadCommandImpl <em>Load Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.LoadCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getLoadCommand()
   * @generated
   */
  int LOAD_COMMAND = 7;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_COMMAND__VAR = CSV_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Load Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_COMMAND_FEATURE_COUNT = CSV_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.StoreCommandImpl <em>Store Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.StoreCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getStoreCommand()
   * @generated
   */
  int STORE_COMMAND = 8;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_COMMAND__VAR = CSV_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Store Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_COMMAND_FEATURE_COUNT = CSV_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.CreateCommandImpl <em>Create Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.CreateCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCreateCommand()
   * @generated
   */
  int CREATE_COMMAND = 9;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_COMMAND__VAR = CSV_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Create Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_COMMAND_FEATURE_COUNT = CSV_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.SetCommandImpl <em>Set Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.SetCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getSetCommand()
   * @generated
   */
  int SET_COMMAND = 10;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_COMMAND__VAR = CSV_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_COMMAND__EXPRESSION = CSV_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Set Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_COMMAND_FEATURE_COUNT = CSV_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.PrintCommandImpl <em>Print Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.PrintCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getPrintCommand()
   * @generated
   */
  int PRINT_COMMAND = 11;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_COMMAND__EXPRESSION = CSV_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_COMMAND_FEATURE_COUNT = CSV_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.ExportCommandImpl <em>Export Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.ExportCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getExportCommand()
   * @generated
   */
  int EXPORT_COMMAND = 12;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT_COMMAND__EXPRESSION = CSV_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Export Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT_COMMAND_FEATURE_COUNT = CSV_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.DeleteCommandImpl <em>Delete Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.DeleteCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getDeleteCommand()
   * @generated
   */
  int DELETE_COMMAND = 13;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_COMMAND__EXPRESSION = CSV_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Delete Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_COMMAND_FEATURE_COUNT = CSV_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.AddCommandImpl <em>Add Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.AddCommandImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getAddCommand()
   * @generated
   */
  int ADD_COMMAND = 14;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_COMMAND__OP = CSV_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_COMMAND__EXPRESSION = CSV_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_COMMAND_FEATURE_COUNT = CSV_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.ExpressionImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 15;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.VariableExprImpl <em>Variable Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.VariableExprImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getVariableExpr()
   * @generated
   */
  int VARIABLE_EXPR = 16;

  /**
   * The feature id for the '<em><b>Term</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_EXPR__TERM = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.SelectorImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 17;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__VAR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.RowSelectImpl <em>Row Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.RowSelectImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getRowSelect()
   * @generated
   */
  int ROW_SELECT = 18;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SELECT__VAR = SELECTOR__VAR;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SELECT__EXPRESSION = SELECTOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Row Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SELECT_FEATURE_COUNT = SELECTOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.ColSelectImpl <em>Col Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.ColSelectImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getColSelect()
   * @generated
   */
  int COL_SELECT = 19;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_SELECT__VAR = SELECTOR__VAR;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_SELECT__EXPRESSION = SELECTOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Col Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_SELECT_FEATURE_COUNT = SELECTOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.CellSelectImpl <em>Cell Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.CellSelectImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCellSelect()
   * @generated
   */
  int CELL_SELECT = 20;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_SELECT__VAR = SELECTOR__VAR;

  /**
   * The feature id for the '<em><b>Expression Row</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_SELECT__EXPRESSION_ROW = SELECTOR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expression Col</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_SELECT__EXPRESSION_COL = SELECTOR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cell Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_SELECT_FEATURE_COUNT = SELECTOR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.FieldSelectImpl <em>Field Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.FieldSelectImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getFieldSelect()
   * @generated
   */
  int FIELD_SELECT = 21;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_SELECT__VAR = SELECTOR__VAR;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_SELECT__EXPRESSION = SELECTOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Field Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_SELECT_FEATURE_COUNT = SELECTOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.CountExprImpl <em>Count Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.CountExprImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCountExpr()
   * @generated
   */
  int COUNT_EXPR = 22;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_EXPR__VAR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_EXPR__EXPRESSION = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Count Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.OrImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getOr()
   * @generated
   */
  int OR = 23;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.AndImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getAnd()
   * @generated
   */
  int AND = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.EqualityImpl <em>Equality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.EqualityImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getEquality()
   * @generated
   */
  int EQUALITY = 25;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Equality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.ComparisonImpl <em>Comparison</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.ComparisonImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getComparison()
   * @generated
   */
  int COMPARISON = 26;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comparison</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.PlusImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getPlus()
   * @generated
   */
  int PLUS = 27;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.MulOrDivImpl <em>Mul Or Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.MulOrDivImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getMulOrDiv()
   * @generated
   */
  int MUL_OR_DIV = 28;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Mul Or Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.NotImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getNot()
   * @generated
   */
  int NOT = 29;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__EXPRESSION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.IntConstantImpl <em>Int Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.IntConstantImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getIntConstant()
   * @generated
   */
  int INT_CONSTANT = 30;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.StringConstantImpl <em>String Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.StringConstantImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getStringConstant()
   * @generated
   */
  int STRING_CONSTANT = 31;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.agicquel.csvs.csvs.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.agicquel.csvs.csvs.impl.BoolConstantImpl
   * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getBoolConstant()
   * @generated
   */
  int BOOL_CONSTANT = 32;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see com.agicquel.csvs.csvs.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link com.agicquel.csvs.csvs.Program#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see com.agicquel.csvs.csvs.Program#getCommands()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Commands();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see com.agicquel.csvs.csvs.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see com.agicquel.csvs.csvs.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.ControlCommand <em>Control Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Control Command</em>'.
   * @see com.agicquel.csvs.csvs.ControlCommand
   * @generated
   */
  EClass getControlCommand();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.ControlCommand#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see com.agicquel.csvs.csvs.ControlCommand#getCond()
   * @see #getControlCommand()
   * @generated
   */
  EReference getControlCommand_Cond();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.WhileCommand <em>While Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While Command</em>'.
   * @see com.agicquel.csvs.csvs.WhileCommand
   * @generated
   */
  EClass getWhileCommand();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.WhileCommand#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see com.agicquel.csvs.csvs.WhileCommand#getBody()
   * @see #getWhileCommand()
   * @generated
   */
  EReference getWhileCommand_Body();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.IfCommand <em>If Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Command</em>'.
   * @see com.agicquel.csvs.csvs.IfCommand
   * @generated
   */
  EClass getIfCommand();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.IfCommand#getThenBody <em>Then Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Body</em>'.
   * @see com.agicquel.csvs.csvs.IfCommand#getThenBody()
   * @see #getIfCommand()
   * @generated
   */
  EReference getIfCommand_ThenBody();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.IfCommand#getElseBody <em>Else Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Body</em>'.
   * @see com.agicquel.csvs.csvs.IfCommand#getElseBody()
   * @see #getIfCommand()
   * @generated
   */
  EReference getIfCommand_ElseBody();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.CsvCommand <em>Csv Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Csv Command</em>'.
   * @see com.agicquel.csvs.csvs.CsvCommand
   * @generated
   */
  EClass getCsvCommand();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.LoadCommand <em>Load Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Load Command</em>'.
   * @see com.agicquel.csvs.csvs.LoadCommand
   * @generated
   */
  EClass getLoadCommand();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.LoadCommand#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see com.agicquel.csvs.csvs.LoadCommand#getVar()
   * @see #getLoadCommand()
   * @generated
   */
  EAttribute getLoadCommand_Var();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.StoreCommand <em>Store Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store Command</em>'.
   * @see com.agicquel.csvs.csvs.StoreCommand
   * @generated
   */
  EClass getStoreCommand();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.StoreCommand#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see com.agicquel.csvs.csvs.StoreCommand#getVar()
   * @see #getStoreCommand()
   * @generated
   */
  EAttribute getStoreCommand_Var();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.CreateCommand <em>Create Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Command</em>'.
   * @see com.agicquel.csvs.csvs.CreateCommand
   * @generated
   */
  EClass getCreateCommand();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.CreateCommand#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see com.agicquel.csvs.csvs.CreateCommand#getVar()
   * @see #getCreateCommand()
   * @generated
   */
  EAttribute getCreateCommand_Var();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.SetCommand <em>Set Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Set Command</em>'.
   * @see com.agicquel.csvs.csvs.SetCommand
   * @generated
   */
  EClass getSetCommand();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.SetCommand#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see com.agicquel.csvs.csvs.SetCommand#getVar()
   * @see #getSetCommand()
   * @generated
   */
  EReference getSetCommand_Var();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.SetCommand#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.SetCommand#getExpression()
   * @see #getSetCommand()
   * @generated
   */
  EReference getSetCommand_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.PrintCommand <em>Print Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print Command</em>'.
   * @see com.agicquel.csvs.csvs.PrintCommand
   * @generated
   */
  EClass getPrintCommand();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.PrintCommand#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.PrintCommand#getExpression()
   * @see #getPrintCommand()
   * @generated
   */
  EReference getPrintCommand_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.ExportCommand <em>Export Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Export Command</em>'.
   * @see com.agicquel.csvs.csvs.ExportCommand
   * @generated
   */
  EClass getExportCommand();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.ExportCommand#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.ExportCommand#getExpression()
   * @see #getExportCommand()
   * @generated
   */
  EReference getExportCommand_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.DeleteCommand <em>Delete Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delete Command</em>'.
   * @see com.agicquel.csvs.csvs.DeleteCommand
   * @generated
   */
  EClass getDeleteCommand();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.DeleteCommand#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.DeleteCommand#getExpression()
   * @see #getDeleteCommand()
   * @generated
   */
  EReference getDeleteCommand_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.AddCommand <em>Add Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Command</em>'.
   * @see com.agicquel.csvs.csvs.AddCommand
   * @generated
   */
  EClass getAddCommand();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.AddCommand#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.agicquel.csvs.csvs.AddCommand#getOp()
   * @see #getAddCommand()
   * @generated
   */
  EAttribute getAddCommand_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.AddCommand#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.AddCommand#getExpression()
   * @see #getAddCommand()
   * @generated
   */
  EReference getAddCommand_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.VariableExpr <em>Variable Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Expr</em>'.
   * @see com.agicquel.csvs.csvs.VariableExpr
   * @generated
   */
  EClass getVariableExpr();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.VariableExpr#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Term</em>'.
   * @see com.agicquel.csvs.csvs.VariableExpr#getTerm()
   * @see #getVariableExpr()
   * @generated
   */
  EAttribute getVariableExpr_Term();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see com.agicquel.csvs.csvs.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.Selector#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see com.agicquel.csvs.csvs.Selector#getVar()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Var();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.RowSelect <em>Row Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Select</em>'.
   * @see com.agicquel.csvs.csvs.RowSelect
   * @generated
   */
  EClass getRowSelect();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.RowSelect#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.RowSelect#getExpression()
   * @see #getRowSelect()
   * @generated
   */
  EReference getRowSelect_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.ColSelect <em>Col Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Col Select</em>'.
   * @see com.agicquel.csvs.csvs.ColSelect
   * @generated
   */
  EClass getColSelect();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.ColSelect#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.ColSelect#getExpression()
   * @see #getColSelect()
   * @generated
   */
  EReference getColSelect_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.CellSelect <em>Cell Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell Select</em>'.
   * @see com.agicquel.csvs.csvs.CellSelect
   * @generated
   */
  EClass getCellSelect();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.CellSelect#getExpressionRow <em>Expression Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression Row</em>'.
   * @see com.agicquel.csvs.csvs.CellSelect#getExpressionRow()
   * @see #getCellSelect()
   * @generated
   */
  EReference getCellSelect_ExpressionRow();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.CellSelect#getExpressionCol <em>Expression Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression Col</em>'.
   * @see com.agicquel.csvs.csvs.CellSelect#getExpressionCol()
   * @see #getCellSelect()
   * @generated
   */
  EReference getCellSelect_ExpressionCol();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.FieldSelect <em>Field Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field Select</em>'.
   * @see com.agicquel.csvs.csvs.FieldSelect
   * @generated
   */
  EClass getFieldSelect();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.FieldSelect#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.FieldSelect#getExpression()
   * @see #getFieldSelect()
   * @generated
   */
  EReference getFieldSelect_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.CountExpr <em>Count Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Count Expr</em>'.
   * @see com.agicquel.csvs.csvs.CountExpr
   * @generated
   */
  EClass getCountExpr();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.CountExpr#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see com.agicquel.csvs.csvs.CountExpr#getVar()
   * @see #getCountExpr()
   * @generated
   */
  EAttribute getCountExpr_Var();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.CountExpr#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.CountExpr#getExpression()
   * @see #getCountExpr()
   * @generated
   */
  EReference getCountExpr_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see com.agicquel.csvs.csvs.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.agicquel.csvs.csvs.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.agicquel.csvs.csvs.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see com.agicquel.csvs.csvs.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.agicquel.csvs.csvs.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.agicquel.csvs.csvs.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Equality <em>Equality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equality</em>'.
   * @see com.agicquel.csvs.csvs.Equality
   * @generated
   */
  EClass getEquality();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.Equality#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.agicquel.csvs.csvs.Equality#getLeft()
   * @see #getEquality()
   * @generated
   */
  EReference getEquality_Left();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.Equality#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.agicquel.csvs.csvs.Equality#getOp()
   * @see #getEquality()
   * @generated
   */
  EAttribute getEquality_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.Equality#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.agicquel.csvs.csvs.Equality#getRight()
   * @see #getEquality()
   * @generated
   */
  EReference getEquality_Right();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison</em>'.
   * @see com.agicquel.csvs.csvs.Comparison
   * @generated
   */
  EClass getComparison();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.Comparison#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.agicquel.csvs.csvs.Comparison#getLeft()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_Left();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.Comparison#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.agicquel.csvs.csvs.Comparison#getOp()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.Comparison#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.agicquel.csvs.csvs.Comparison#getRight()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_Right();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see com.agicquel.csvs.csvs.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.agicquel.csvs.csvs.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.Plus#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.agicquel.csvs.csvs.Plus#getOp()
   * @see #getPlus()
   * @generated
   */
  EAttribute getPlus_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.agicquel.csvs.csvs.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.MulOrDiv <em>Mul Or Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mul Or Div</em>'.
   * @see com.agicquel.csvs.csvs.MulOrDiv
   * @generated
   */
  EClass getMulOrDiv();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.MulOrDiv#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.agicquel.csvs.csvs.MulOrDiv#getLeft()
   * @see #getMulOrDiv()
   * @generated
   */
  EReference getMulOrDiv_Left();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.MulOrDiv#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.agicquel.csvs.csvs.MulOrDiv#getOp()
   * @see #getMulOrDiv()
   * @generated
   */
  EAttribute getMulOrDiv_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.MulOrDiv#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.agicquel.csvs.csvs.MulOrDiv#getRight()
   * @see #getMulOrDiv()
   * @generated
   */
  EReference getMulOrDiv_Right();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see com.agicquel.csvs.csvs.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for the containment reference '{@link com.agicquel.csvs.csvs.Not#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.agicquel.csvs.csvs.Not#getExpression()
   * @see #getNot()
   * @generated
   */
  EReference getNot_Expression();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.IntConstant <em>Int Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Constant</em>'.
   * @see com.agicquel.csvs.csvs.IntConstant
   * @generated
   */
  EClass getIntConstant();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.IntConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.agicquel.csvs.csvs.IntConstant#getValue()
   * @see #getIntConstant()
   * @generated
   */
  EAttribute getIntConstant_Value();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.StringConstant <em>String Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Constant</em>'.
   * @see com.agicquel.csvs.csvs.StringConstant
   * @generated
   */
  EClass getStringConstant();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.StringConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.agicquel.csvs.csvs.StringConstant#getValue()
   * @see #getStringConstant()
   * @generated
   */
  EAttribute getStringConstant_Value();

  /**
   * Returns the meta object for class '{@link com.agicquel.csvs.csvs.BoolConstant <em>Bool Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Constant</em>'.
   * @see com.agicquel.csvs.csvs.BoolConstant
   * @generated
   */
  EClass getBoolConstant();

  /**
   * Returns the meta object for the attribute '{@link com.agicquel.csvs.csvs.BoolConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.agicquel.csvs.csvs.BoolConstant#getValue()
   * @see #getBoolConstant()
   * @generated
   */
  EAttribute getBoolConstant_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CsvsFactory getCsvsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.ProgramImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__COMMANDS = eINSTANCE.getProgram_Commands();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.CommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.BlockImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.ControlCommandImpl <em>Control Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.ControlCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getControlCommand()
     * @generated
     */
    EClass CONTROL_COMMAND = eINSTANCE.getControlCommand();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTROL_COMMAND__COND = eINSTANCE.getControlCommand_Cond();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.WhileCommandImpl <em>While Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.WhileCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getWhileCommand()
     * @generated
     */
    EClass WHILE_COMMAND = eINSTANCE.getWhileCommand();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_COMMAND__BODY = eINSTANCE.getWhileCommand_Body();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.IfCommandImpl <em>If Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.IfCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getIfCommand()
     * @generated
     */
    EClass IF_COMMAND = eINSTANCE.getIfCommand();

    /**
     * The meta object literal for the '<em><b>Then Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_COMMAND__THEN_BODY = eINSTANCE.getIfCommand_ThenBody();

    /**
     * The meta object literal for the '<em><b>Else Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_COMMAND__ELSE_BODY = eINSTANCE.getIfCommand_ElseBody();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.CsvCommandImpl <em>Csv Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.CsvCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCsvCommand()
     * @generated
     */
    EClass CSV_COMMAND = eINSTANCE.getCsvCommand();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.LoadCommandImpl <em>Load Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.LoadCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getLoadCommand()
     * @generated
     */
    EClass LOAD_COMMAND = eINSTANCE.getLoadCommand();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_COMMAND__VAR = eINSTANCE.getLoadCommand_Var();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.StoreCommandImpl <em>Store Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.StoreCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getStoreCommand()
     * @generated
     */
    EClass STORE_COMMAND = eINSTANCE.getStoreCommand();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE_COMMAND__VAR = eINSTANCE.getStoreCommand_Var();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.CreateCommandImpl <em>Create Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.CreateCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCreateCommand()
     * @generated
     */
    EClass CREATE_COMMAND = eINSTANCE.getCreateCommand();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE_COMMAND__VAR = eINSTANCE.getCreateCommand_Var();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.SetCommandImpl <em>Set Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.SetCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getSetCommand()
     * @generated
     */
    EClass SET_COMMAND = eINSTANCE.getSetCommand();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET_COMMAND__VAR = eINSTANCE.getSetCommand_Var();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET_COMMAND__EXPRESSION = eINSTANCE.getSetCommand_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.PrintCommandImpl <em>Print Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.PrintCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getPrintCommand()
     * @generated
     */
    EClass PRINT_COMMAND = eINSTANCE.getPrintCommand();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT_COMMAND__EXPRESSION = eINSTANCE.getPrintCommand_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.ExportCommandImpl <em>Export Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.ExportCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getExportCommand()
     * @generated
     */
    EClass EXPORT_COMMAND = eINSTANCE.getExportCommand();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPORT_COMMAND__EXPRESSION = eINSTANCE.getExportCommand_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.DeleteCommandImpl <em>Delete Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.DeleteCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getDeleteCommand()
     * @generated
     */
    EClass DELETE_COMMAND = eINSTANCE.getDeleteCommand();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE_COMMAND__EXPRESSION = eINSTANCE.getDeleteCommand_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.AddCommandImpl <em>Add Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.AddCommandImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getAddCommand()
     * @generated
     */
    EClass ADD_COMMAND = eINSTANCE.getAddCommand();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_COMMAND__OP = eINSTANCE.getAddCommand_Op();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_COMMAND__EXPRESSION = eINSTANCE.getAddCommand_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.ExpressionImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.VariableExprImpl <em>Variable Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.VariableExprImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getVariableExpr()
     * @generated
     */
    EClass VARIABLE_EXPR = eINSTANCE.getVariableExpr();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_EXPR__TERM = eINSTANCE.getVariableExpr_Term();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.SelectorImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__VAR = eINSTANCE.getSelector_Var();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.RowSelectImpl <em>Row Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.RowSelectImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getRowSelect()
     * @generated
     */
    EClass ROW_SELECT = eINSTANCE.getRowSelect();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_SELECT__EXPRESSION = eINSTANCE.getRowSelect_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.ColSelectImpl <em>Col Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.ColSelectImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getColSelect()
     * @generated
     */
    EClass COL_SELECT = eINSTANCE.getColSelect();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COL_SELECT__EXPRESSION = eINSTANCE.getColSelect_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.CellSelectImpl <em>Cell Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.CellSelectImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCellSelect()
     * @generated
     */
    EClass CELL_SELECT = eINSTANCE.getCellSelect();

    /**
     * The meta object literal for the '<em><b>Expression Row</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL_SELECT__EXPRESSION_ROW = eINSTANCE.getCellSelect_ExpressionRow();

    /**
     * The meta object literal for the '<em><b>Expression Col</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL_SELECT__EXPRESSION_COL = eINSTANCE.getCellSelect_ExpressionCol();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.FieldSelectImpl <em>Field Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.FieldSelectImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getFieldSelect()
     * @generated
     */
    EClass FIELD_SELECT = eINSTANCE.getFieldSelect();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD_SELECT__EXPRESSION = eINSTANCE.getFieldSelect_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.CountExprImpl <em>Count Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.CountExprImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getCountExpr()
     * @generated
     */
    EClass COUNT_EXPR = eINSTANCE.getCountExpr();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COUNT_EXPR__VAR = eINSTANCE.getCountExpr_Var();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COUNT_EXPR__EXPRESSION = eINSTANCE.getCountExpr_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.OrImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.AndImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.EqualityImpl <em>Equality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.EqualityImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getEquality()
     * @generated
     */
    EClass EQUALITY = eINSTANCE.getEquality();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY__LEFT = eINSTANCE.getEquality_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUALITY__OP = eINSTANCE.getEquality_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY__RIGHT = eINSTANCE.getEquality_Right();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.ComparisonImpl <em>Comparison</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.ComparisonImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getComparison()
     * @generated
     */
    EClass COMPARISON = eINSTANCE.getComparison();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__LEFT = eINSTANCE.getComparison_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__OP = eINSTANCE.getComparison_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__RIGHT = eINSTANCE.getComparison_Right();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.PlusImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLUS__OP = eINSTANCE.getPlus_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.MulOrDivImpl <em>Mul Or Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.MulOrDivImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getMulOrDiv()
     * @generated
     */
    EClass MUL_OR_DIV = eINSTANCE.getMulOrDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MUL_OR_DIV__LEFT = eINSTANCE.getMulOrDiv_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MUL_OR_DIV__OP = eINSTANCE.getMulOrDiv_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MUL_OR_DIV__RIGHT = eINSTANCE.getMulOrDiv_Right();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.NotImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT__EXPRESSION = eINSTANCE.getNot_Expression();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.IntConstantImpl <em>Int Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.IntConstantImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getIntConstant()
     * @generated
     */
    EClass INT_CONSTANT = eINSTANCE.getIntConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_CONSTANT__VALUE = eINSTANCE.getIntConstant_Value();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.StringConstantImpl <em>String Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.StringConstantImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getStringConstant()
     * @generated
     */
    EClass STRING_CONSTANT = eINSTANCE.getStringConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_CONSTANT__VALUE = eINSTANCE.getStringConstant_Value();

    /**
     * The meta object literal for the '{@link com.agicquel.csvs.csvs.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.agicquel.csvs.csvs.impl.BoolConstantImpl
     * @see com.agicquel.csvs.csvs.impl.CsvsPackageImpl#getBoolConstant()
     * @generated
     */
    EClass BOOL_CONSTANT = eINSTANCE.getBoolConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_CONSTANT__VALUE = eINSTANCE.getBoolConstant_Value();

  }

} //CsvsPackage
