/**
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.csvs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.agicquel.csvs.csvs.DeleteCommand#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see com.agicquel.csvs.csvs.CsvsPackage#getDeleteCommand()
 * @model
 * @generated
 */
public interface DeleteCommand extends CsvCommand
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(CsvsExpr)
   * @see com.agicquel.csvs.csvs.CsvsPackage#getDeleteCommand_Expression()
   * @model containment="true"
   * @generated
   */
  CsvsExpr getExpression();

  /**
   * Sets the value of the '{@link com.agicquel.csvs.csvs.DeleteCommand#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(CsvsExpr value);

} // DeleteCommand
