/**
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.csvs;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plus Or Minus Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.agicquel.csvs.csvs.PlusOrMinusExpr#getLeft <em>Left</em>}</li>
 *   <li>{@link com.agicquel.csvs.csvs.PlusOrMinusExpr#getOp <em>Op</em>}</li>
 *   <li>{@link com.agicquel.csvs.csvs.PlusOrMinusExpr#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see com.agicquel.csvs.csvs.CsvsPackage#getPlusOrMinusExpr()
 * @model
 * @generated
 */
public interface PlusOrMinusExpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(MulOrDivExpr)
   * @see com.agicquel.csvs.csvs.CsvsPackage#getPlusOrMinusExpr_Left()
   * @model containment="true"
   * @generated
   */
  MulOrDivExpr getLeft();

  /**
   * Sets the value of the '{@link com.agicquel.csvs.csvs.PlusOrMinusExpr#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(MulOrDivExpr value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute list.
   * @see com.agicquel.csvs.csvs.CsvsPackage#getPlusOrMinusExpr_Op()
   * @model unique="false"
   * @generated
   */
  EList<String> getOp();

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link com.agicquel.csvs.csvs.MulOrDivExpr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see com.agicquel.csvs.csvs.CsvsPackage#getPlusOrMinusExpr_Right()
   * @model containment="true"
   * @generated
   */
  EList<MulOrDivExpr> getRight();

} // PlusOrMinusExpr
