/**
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.csvs;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.agicquel.csvs.csvs.CsvsPackage#getPrimaryExpr()
 * @model
 * @generated
 */
public interface PrimaryExpr extends EObject
{
} // PrimaryExpr
