/**
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.csvs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rename Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.agicquel.csvs.csvs.RenameCommand#getExpr <em>Expr</em>}</li>
 *   <li>{@link com.agicquel.csvs.csvs.RenameCommand#getOldname <em>Oldname</em>}</li>
 *   <li>{@link com.agicquel.csvs.csvs.RenameCommand#getNewname <em>Newname</em>}</li>
 * </ul>
 *
 * @see com.agicquel.csvs.csvs.CsvsPackage#getRenameCommand()
 * @model
 * @generated
 */
public interface RenameCommand extends CsvCommand
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(CsvsExpr)
   * @see com.agicquel.csvs.csvs.CsvsPackage#getRenameCommand_Expr()
   * @model containment="true"
   * @generated
   */
  CsvsExpr getExpr();

  /**
   * Sets the value of the '{@link com.agicquel.csvs.csvs.RenameCommand#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(CsvsExpr value);

  /**
   * Returns the value of the '<em><b>Oldname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oldname</em>' containment reference.
   * @see #setOldname(Expression)
   * @see com.agicquel.csvs.csvs.CsvsPackage#getRenameCommand_Oldname()
   * @model containment="true"
   * @generated
   */
  Expression getOldname();

  /**
   * Sets the value of the '{@link com.agicquel.csvs.csvs.RenameCommand#getOldname <em>Oldname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Oldname</em>' containment reference.
   * @see #getOldname()
   * @generated
   */
  void setOldname(Expression value);

  /**
   * Returns the value of the '<em><b>Newname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Newname</em>' containment reference.
   * @see #setNewname(Expression)
   * @see com.agicquel.csvs.csvs.CsvsPackage#getRenameCommand_Newname()
   * @model containment="true"
   * @generated
   */
  Expression getNewname();

  /**
   * Sets the value of the '{@link com.agicquel.csvs.csvs.RenameCommand#getNewname <em>Newname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Newname</em>' containment reference.
   * @see #getNewname()
   * @generated
   */
  void setNewname(Expression value);

} // RenameCommand
