/*
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.ide;

import com.agicquel.csvs.CSVsRuntimeModule;
import com.agicquel.csvs.CSVsStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CSVsIdeSetup extends CSVsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CSVsRuntimeModule(), new CSVsIdeModule()));
	}
	
}
