/*
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.ui;

import com.agicquel.csvs.ui.internal.CsvsActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CSVsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CsvsActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CsvsActivator activator = CsvsActivator.getInstance();
		return activator != null ? activator.getInjector(CsvsActivator.COM_AGICQUEL_CSVS_CSVS) : null;
	}

}
