/**
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.csvs.impl;

import com.agicquel.csvs.csvs.AtomicExpr;
import com.agicquel.csvs.csvs.CsvsPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atomic Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AtomicExprImpl extends CsvsExprImpl implements AtomicExpr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtomicExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CsvsPackage.Literals.ATOMIC_EXPR;
  }

} //AtomicExprImpl
