/*
 * generated by Xtext 2.23.0
 */
package com.agicquel.csvs.ui.tests;

import com.agicquel.csvs.ui.internal.CsvsActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CSVsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CsvsActivator.getInstance().getInjector("com.agicquel.csvs.CSVs");
	}

}
